# Generated by Django 6.0.6 on 2026-07-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_conversation_needs_human_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_score', models.IntegerField(default=100)),
                ('search_score', models.IntegerField(default=100)),
                ('product_info_score', models.IntegerField(default=100)),
                ('comparison_score', models.IntegerField(default=100)),
                ('order_score', models.IntegerField(default=100)),
                ('overall_score', models.FloatField(default=100.0)),
                ('has_hallucination', models.BooleanField(default=False)),
                ('evaluation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='products.conversation')),
            ],
        ),
    ]
