# Generated by Django 6.0.6 on 2026-07-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_conversationevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='internal_context',
            field=models.TextField(blank=True),
        ),
    ]
