# Generated by Django 6.0.6 on 2026-07-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_message_internal_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bot_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.conversation'),
        ),
    ]
