# Generated by Django 6.0.6 on 2026-07-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_orderitem_product_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bottle_type',
            field=models.CharField(choices=[('normal', 'عادية'), ('original', 'أوريجينال')], default='normal', max_length=20),
        ),
    ]
