# Generated by Django 6.0.6 on 2026-07-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_original_bottles_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='concentration_percentage',
            field=models.PositiveIntegerField(default=30, help_text='نسبة الزيت للزجاجة (مثال: 30%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='oil_stock_grams',
            field=models.PositiveIntegerField(default=0, help_text='رصيد الزيت العطري بالجرام'),
        ),
    ]
