# Generated by Django 6.0.6 on 2026-07-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productvariant_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['bottle_type', 'volume']},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_bottles_stock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='bottle_type',
            field=models.CharField(choices=[('normal', 'زجاجة المحل'), ('original', 'أوريجينال')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='مخزون الزجاجات (للأوريجينال فقط)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'volume', 'bottle_type')},
        ),
    ]
