# Generated by Django 6.0.6 on 2026-07-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='platform',
            field=models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram')], default='web', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='platform_sender_id',
            field=models.CharField(blank=True, help_text='External user ID from the platform', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='instagram_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='meta_access_token',
            field=models.TextField(blank=True, help_text='Graph API Access Token'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='meta_app_secret',
            field=models.CharField(blank=True, help_text='App Secret for signature validation', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='meta_verify_token',
            field=models.CharField(blank=True, help_text='Token for webhook verification', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
