# Generated by Django 6.0.6 on 2026-07-21 07:45

import django.db.models.deletion
import products.encryption
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_conversation_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='meta_access_token',
            field=products.encryption.EncryptedTextField(blank=True, help_text='Graph API Access Token'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='meta_app_secret',
            field=products.encryption.EncryptedCharField(blank=True, help_text='App Secret for signature validation', max_length=500),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('handoff', 'Human Handoff Required'), ('new_order', 'New Order'), ('low_stock', 'Low Stock')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
