# Generated by Django 6.0.6 on 2026-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_owner_notification_encrypted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
