# Generated by Django 6.0.6 on 2026-07-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_order_secondary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='perfume_type',
            field=models.CharField(blank=True, choices=[('oriental', 'عطور شرقية'), ('western', 'عطور غربية'), ('niche', 'نيش'), ('ultra_niche', 'الترا نيش (بريميوم)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='bottle_type',
            field=models.CharField(choices=[('normal', 'زجاجة البراند'), ('original', 'أوريجينال')], default='normal', max_length=20),
        ),
    ]
