# Generated by Django 6.0.6 on 2026-08-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_perfume_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='meta_access_token',
            field=models.TextField(blank=True, help_text='Graph API Access Token'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='meta_app_secret',
            field=models.CharField(blank=True, help_text='App Secret for signature validation', max_length=500),
        ),
    ]
