# Generated by Django 6.0.6 on 2026-08-05 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_perfume_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='السؤال كما يظهر للإدارة', max_length=500)),
                ('keywords', models.TextField(help_text='كلمات مفتاحية مفصولة بفاصلة (مثال: شحن, توصيل, توصل)')),
                ('answer', models.TextField(help_text='الرد الثابت')),
                ('priority', models.IntegerField(default=0, help_text='أولوية أعلى = يتشيك الأول')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_faqs', to='products.store')),
            ],
            options={
                'verbose_name': 'سؤال ثابت',
                'verbose_name_plural': 'الأسئلة الثابتة',
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
