# Generated by Django 6.0.6 on 2026-08-12 14:10

import products.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_storesettings_comment_reply_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='meta_access_token',
            field=products.encryption.EncryptedTextField(blank=True, help_text='WhatsApp Graph API Access Token'),
        ),
    ]
