# Generated by Django 6.0.6 on 2026-08-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='تعليمات الدفع اللي تظهر للعميل بعد تأكيد الطلب (العربون، طرق التحويل، سياسة الإلغاء). لو فاضية، البوت هيقول للعميل إن فريق المبيعات هيتواصل معاه بتفاصيل الدفع.'),
        ),
    ]
