# Generated by Django 6.0.6 on 2026-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_seed_legacy_payment_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='bottle_image_url',
            field=models.URLField(blank=True, help_text='لينك صورة الزجاجات والبوكس بتاع الستور. لو فاضية، البوت مش هيبعت صور.', max_length=500),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='business_facts',
            field=models.TextField(blank=True, help_text='حقائق خاصة بالستور يقولها البوت للعميل (نسب الزيت، الأحجام المتاحة، هل فيه فرع على أرض الواقع، نسبة تشابه التركيب). لو فاضية، البوت مش هيدّعي أي حاجة من دي.'),
        ),
    ]
