# Generated by Django 6.0.6 on 2026-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_seed_legacy_store_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='platform',
            field=models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('facebook', 'Facebook Comment')], default='web', max_length=50),
        ),
    ]
