# Generated by Django 6.0.6 on 2026-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_conversation_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='facebook_page_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='instagram_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='meta_verify_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token for webhook verification', max_length=100),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['store', 'platform', 'platform_sender_id', '-created_at'], name='conv_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['store', 'needs_human'], name='conv_handoff_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='msg_history_idx'),
        ),
    ]
