# Generated by Django 6.0.6 on 2026-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_storesettings_facebook_page_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('handoff', 'Human Handoff Required'), ('new_order', 'New Order'), ('low_stock', 'Low Stock'), ('delivery_failed', 'Reply Not Delivered')], max_length=50),
        ),
    ]
