# Generated by Django 6.0.6 on 2026-08-22 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_encrypt_customer_pii'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pending_product',
            field=models.ForeignKey(blank=True, help_text='عطر اختاره العميل لكن لسه محددش الحجم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_in_carts', to='products.product'),
        ),
    ]
