# Generated by Django 6.0.6 on 2026-08-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_cart_pending_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='concentration_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oil_stock_grams',
        ),
    ]
