# Generated by Django 6.0.6 on 2026-09-12 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_product_concentration_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('post_id', models.CharField(db_index=True, help_text='Facebook post ID (PageID_PostID) أو Instagram media ID', max_length=255)),
                ('label', models.CharField(blank=True, help_text='وصف اختياري للبوست (مثلاً: بوست صيف 2026)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_rules', to='products.store')),
            ],
            options={
                'verbose_name': 'قاعدة رد على البوست',
                'verbose_name_plural': 'قواعد الرد على البوستات',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('store', 'platform', 'post_id'), name='one_rule_per_post')],
            },
        ),
    ]
