# Generated by Django 6.0.6 on 2026-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_post_comment_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
