# Generated by Django 6.0.6 on 2026-10-06 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_lines(apps, schema_editor):
    Cart = apps.get_model("products", "Cart")
    CartItem = apps.get_model("products", "CartItem")
    for cart in Cart.objects.using(schema_editor.connection.alias).filter(pending_product__isnull=False).select_related("pending_product").iterator():
        cart.pending_items = [{"line_id": uuid.uuid4().hex, "name": cart.pending_product.name, "quantity": 1}]
        cart.save(update_fields=["pending_items"], using=schema_editor.connection.alias)
    for line in CartItem.objects.using(schema_editor.connection.alias).all().iterator():
        line.line_id = uuid.uuid4().hex
        line.save(update_fields=["line_id"], using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_add_attachment_url_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pending_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cart',
            name='quote',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='line_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sales_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_parts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notification_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('source_key', models.CharField(max_length=64)),
                ('sender_id', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('attachment_url', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.conversation')),
                ('reply_message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_event', to='products.message')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.store')),
                ('user_message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_event', to='products.message')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'status', 'id'], name='inbound_pending_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'platform', 'source_key'), name='unique_inbound_source')],
            },
        ),
        migrations.RunPython(backfill_lines, migrations.RunPython.noop),
    ]
