"""
Django settings for perfume_ai project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url
from datetime import timedelta
# 1. Load the environment variables from the .env file
# This must be called before trying to access the variables.
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL")
# Stronger model for reasoning-heavy calls. Unset falls back to OPENAI_MODEL;
# see products.services.ai.client._profiles.
OPENAI_SMART_MODEL = os.environ.get("OPENAI_SMART_MODEL")
OPENAI_TEMPERATURE = float(os.environ.get("OPENAI_TEMPERATURE", 1.0))

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=True in .env for development
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CORS configuration — set CORS_ALLOWED_ORIGINS in .env for production (comma-separated)
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if os.environ.get('CORS_ALLOWED_ORIGINS') else []
CORS_ALLOW_ALL_ORIGINS = True if DEBUG and not CORS_ALLOWED_ORIGINS else False

CSRF_TRUSTED_ORIGINS = ['https://*.railway.app', 'https://*.up.railway.app']

# Allow the custom X-API-Key header from cross-origin widget requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "products",
    "dashboard",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'perfume_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'perfume_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
'default': dj_database_url.config(
    engine='django.db.backends.postgresql',
    default=os.environ.get('DATABASE_URL'),
    conn_max_age=60,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Widget JS must never be cached — clients embed it with a fixed URL
WHITENOISE_MAX_AGE = 0
WHITENOISE_KEEP_ONLY_HASHED_FILES = False

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DRF Rate Limiting
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'store': '60/minute',
        'chat': '30/minute',
        'webhook': '200/minute',
    }
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Email Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.resend.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'resend')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Perfume AI <noreply@perfumeai.com>')

# Password reset token expiry (1 hour)
PASSWORD_RESET_TIMEOUT = 3600

# Field Encryption Key (for encrypting sensitive data like Meta tokens)
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')

# Sentry Error Monitoring
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=0.2,
        send_default_pii=False,
    )

X_FRAME_OPTIONS = 'SAMEORIGIN'

# ---------------------------------------------------------------------------
# Meta webhook security
# ---------------------------------------------------------------------------
# Webhook payloads are authenticated by the X-Hub-Signature-256 header, checked
# against each store's meta_app_secret. When a store has no secret configured
# the request is let through so existing integrations keep working.
#
# Rollout: leave this False, deploy, and confirm the logs show no
# "signature NOT verified" warnings — that means every live store has a secret
# and real traffic is passing the check. Then set
# META_REQUIRE_WEBHOOK_SIGNATURE=True to reject unsigned webhooks outright.
META_REQUIRE_WEBHOOK_SIGNATURE = os.environ.get(
    'META_REQUIRE_WEBHOOK_SIGNATURE', 'False'
).lower() in ('true', '1', 'yes')

# ---------------------------------------------------------------------------
# Cache
# ---------------------------------------------------------------------------
# REDIS_URL is automatically set by Railway when you add a Redis service.
# On a VPS, set it manually in your .env: REDIS_URL=redis://localhost:6379/0
REDIS_URL = os.environ.get('REDIS_URL')

# DRF keeps its throttle counters in the default cache. With a per-process
# backend every gunicorn worker counts separately, so the effective limit is
# workers × rate and it resets on each deploy. Redis makes the counts shared.
# ResilientRedisCache degrades to a no-op if Redis is down rather than 500ing
# every throttled request — see products/cache.py.
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'products.cache.ResilientRedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    # No Redis configured — local development. Throttle counts are per-process
    # here, which is fine for a single runserver but must not be relied on in
    # production.
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# ---------------------------------------------------------------------------
# Celery Configuration
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = REDIS_URL or 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = REDIS_URL or 'redis://localhost:6379/0'

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Acknowledge tasks only after completion (prevents message loss on worker crash)
CELERY_TASK_ACKS_LATE = True

# One retry attempt won't hog the worker — keep concurrency reasonable
CELERY_WORKER_PREFETCH_MULTIPLIER = 1